refine Community-and-related-software.md and tools page
shaarli/Shaarli pull request #1787
Opened 2021-08-22 14:21 UTC by yfdyh000

Rebuild and enhance. Stop hard-coded language in urls, broken Chrome extension url.

Unfortunately, I failed to pass variables to `t()` fun.

2021-09-05 07:38 UTC, ArthurHoaro commented on doc/md/Community-and-related-software.md
> +- [Add to Shaarli](https://chrome.google.com/webstore/detail/add-to-shaarli/jhfblapoehcfajokolimghdfmeeakbee) - lets you add the current tab or a note to your Shaarli instance. Support hotkeys. ![Chr
It would be nice to add the Github repository somehow: https://github.com/burgyl/AddToShaarli

2021-09-05 07:48 UTC, ArthurHoaro commented on tpl/default/tools.html
> +      {'There are many resources that can be used to interact with Shaarli instance, including REST API clients, browser extensions, third-party plugins, scripts running on server and instance runnin
Please avoid very long line and don't hesitate to break lines. 

I don't think the "either on Github or below" here is necessary, there are already a bunch of links. It might be more confusing than helping. In any case the closing parenthesis is misplaced.

2021-09-05 07:50 UTC, ArthurHoaro requested changes
See minor comments but great improvement overall in the tools page.

Also I didn't know that the Chrome extension was outdated, and I had never heard of WebLinks extension, which seems full featured.

2021-11-23 19:14 UTC, nodiscc commented
I made a few improvements https://github.com/shaarli/Shaarli/blob/6c156d0166c9d08366b92001e970e9594c278816/doc/md/Community-and-related-software.md

The cloudron/yunohost look exceedingly large/high. Ideally they would be the same size as shields.io badges

2021-11-23 19:15 UTC, nodiscc commented
(i would have used shields.io badges for cloudron/yunohost but their icons are not available on https://simpleicons.org/ - which is what shields.io uses)

2021-11-23 19:27 UTC, nodiscc commented
Looks good to me now https://github.com/shaarli/Shaarli/blob/d543a86d9b30c85fbb9e4ee479b566ef3cc170b8/doc/md/Community-and-related-software.md. @yfdyh000 can you squash everything to a single commit?

2021-12-17 14:36 UTC, nodiscc commented
@yfdyh000 ping

2022-08-13 08:24 UTC, ArthurHoaro commented
Thanks for working on it @nodiscc. Squashing and merging :+1:

2022-08-13 08:27 UTC, ArthurHoaro approved these changes

2022-08-13 14:12 UTC, merged