Resolve PHP 8.1 deprecations
shaarli/Shaarli pull request #1866
Opened 2022-08-03 11:32 UTC by hazhargaleh

Resolve PHP 8.1 deprecations so we don't have our logs polluted with warnings.

2022-08-03 12:46 UTC, PowerKiKi commented on application/legacy/LegacyLinkDB.php
>       */
Use docblock to document return type until we can enforce it at the language level

```suggestion
     * Iterator - Returns the key of the current element
     *
     * @return int|string
     */
```

2022-08-12 17:06 UTC, ArthurHoaro requested changes
Thanks, that's pretty nice! 
I just have a few minor comments.

On a side note there are a bunch of deprecation comments raised in Slim that should probably be handled at some point as well (not in this PR).

2022-08-12 17:06 UTC, ArthurHoaro commented on application/Utils.php
> +    if (!empty($referer) && (strpos($refererHost ?? '', $host) !== false || startsWith('?', $refererHost))) {
It's probably better to set the default value during assignation the line before.

2022-08-12 17:06 UTC, ArthurHoaro commented on application/helper/ApplicationUtils.php
> +            if (!is_file(realpath($path ?? ''))) {
Same result but it lifts any ambiguity
```suggestion
            if (!is_string($path) || !is_file(realpath($path))) {
```

2022-08-23 09:03 UTC, hazhargaleh commented on application/Utils.php
> +    $needle = $needle ?? '';
Technically speaking any string starts with an empty string, and since `null` is coerced to empty string it's actually correct to return `true`. This is how the PHP 8.0 [`str_starts_with`](https://www.php.net/manual/en/function.str-starts-with.php) works: https://3v4l.org/2meph

Also while it would indeed be better to fix all calling code, I'm afraid we don't know the project well enough to make the correct choice for each call, and this would probably be too much work for us. This is more intended as a quick fix, rather than overhauling the whole typing in the project.

2022-08-23 09:22 UTC, hazhargaleh commented on application/Utils.php
> +    if (!empty($referer) && (strpos($refererHost ?? '', $host) !== false || startsWith('?', $refererHost))) {
We fixed it

2022-09-12 13:17 UTC, hazhargaleh commented
Hello @ArthurHoaro,
Did you have time to review my code?

2022-09-14 06:12 UTC, ArthurHoaro commented on application/Utils.php
> +    $needle = $needle ?? '';
Yes, you are right, I'm too used to work with strict types. This makes complete sense and follow PHP behavior then.
Interesting to note in your example that it's deprecated in 8.1 btw.

2022-09-14 06:16 UTC, ArthurHoaro approved these changes
Thanks again for working on this!

2022-09-14 06:16 UTC, ArthurHoaro commented
Could you squash your commits?

2022-09-14 06:17 UTC, merged